// Map raw model feature names to translation keys for display.
// Keys correspond to raw feature strings returned by the explainer endpoint.
export const FEATURE_LABEL_KEYS: Record<string, string> = {
  "PID": "feature_labels.pid",
  "Alter [J]": "feature_labels.age_years",
  "Seiten": "feature_labels.side",
  "Symptome präoperativ.Geschmack...": "feature_labels.symptom_taste",
  "Symptome präoperativ.Tinnitus...": "feature_labels.symptom_tinnitus",
  "Symptome präoperativ.Schwindel...": "feature_labels.symptom_vertigo",
  "Symptome präoperativ.Otorrhoe...": "feature_labels.symptom_otorrhea",
  "Symptome präoperativ.Kopfschmerzen...": "feature_labels.symptom_headache",
  "Diagnose.Höranamnese.Hörminderung operiertes Ohr...": "feature_labels.hearing_loss_operated",
  "Diagnose.Höranamnese.Zeitpunkt des Hörverlusts (OP-Ohr)...": "feature_labels.hearing_loss_timing_operated",
  "Diagnose.Höranamnese.Beginn der Hörminderung (OP-Ohr)...": "feature_labels.hearing_loss_onset_operated",
  "Diagnose.Höranamnese.Hochgradige Hörminderung oder Taubheit (OP-Ohr)...": "feature_labels.severe_loss_operated",
  "Diagnose.Höranamnese.Hörminderung Gegenohr...": "feature_labels.hearing_loss_contralateral",
  "outcome_measurments.pre.measure.": "feature_labels.outcome_pre_measure",
  "abstand": "feature_labels.interval",
  "Geschlecht_m": "feature_labels.gender_m",
  "Geschlecht_w": "feature_labels.gender_w",
  "Objektive Messungen.LL..._Nicht erhoben": "feature_labels.objective_ll_missing",
  "Objektive Messungen.LL..._Schwelle": "feature_labels.objective_ll_threshold",
  "Objektive Messungen.4000 Hz..._Nicht erhoben": "feature_labels.objective_4000_missing",
  "Objektive Messungen.4000 Hz..._Schwelle": "feature_labels.objective_4000_threshold",
  "Diagnose.Höranamnese.Ursache....Ursache..._unknown": "feature_labels.cause_unknown",
  "Diagnose.Höranamnese.Ursache....Ursache..._Other": "feature_labels.cause_other",
  "Diagnose.Höranamnese.Ursache....Ursache..._Infektiös": "feature_labels.cause_infectious",
  "Diagnose.Höranamnese.Ursache....Ursache..._Hörsturz": "feature_labels.cause_hearing_loss",
  "Diagnose.Höranamnese.Ursache....Ursache..._Syndromal": "feature_labels.cause_syndromic",
  "Diagnose.Höranamnese.Ursache....Ursache..._M. Menière": "feature_labels.cause_meniere",
  "Diagnose.Höranamnese.Ursache....Ursache..._Andere": "feature_labels.cause_other_general",
  "Diagnose.Höranamnese.Versorgung Gegenohr..._CI": "feature_labels.aid_contralateral_ci",
  "Diagnose.Höranamnese.Versorgung Gegenohr..._Hörgerät": "feature_labels.aid_contralateral_hearing_aid",
  "Diagnose.Höranamnese.Versorgung Gegenohr..._Keine Versorgung": "feature_labels.aid_contralateral_none",
  "Diagnose.Höranamnese.Versorgung operiertes Ohr..._Hörgerät": "feature_labels.aid_operated_hearing_aid",
  "Diagnose.Höranamnese.Versorgung operiertes Ohr..._Keine Versorgung": "feature_labels.aid_operated_none",
  "Diagnose.Höranamnese.Versorgung operiertes Ohr..._Nicht erhoben": "feature_labels.aid_operated_missing",
  "Diagnose.Höranamnese.Erwerbsart..._Plötzlich": "feature_labels.acquisition_sudden",
  "Diagnose.Höranamnese.Erwerbsart..._Progredient": "feature_labels.acquisition_progressive",
  "Diagnose.Höranamnese.Erwerbsart..._unknown": "feature_labels.acquisition_unknown",
  "Diagnose.Höranamnese.Art der Hörstörung..._Cochleär": "feature_labels.hearing_type_cochlear",
  "Diagnose.Höranamnese.Art der Hörstörung..._Schallleitung": "feature_labels.hearing_type_conductive",
  "Diagnose.Höranamnese.Art der Hörstörung..._Sonstige": "feature_labels.hearing_type_other",
  "Behandlung/OP.CI Implantation_Behandlung/OP.CI Implantation.Cochlear... Nucleus Profile CI532 (Slim Modiolar)": "feature_labels.implant_ci532",
  "Behandlung/OP.CI Implantation_Behandlung/OP.CI Implantation.Cochlear... Nucleus Profile CI522 (Slim Straight)": "feature_labels.implant_ci522",
  "Behandlung/OP.CI Implantation_Behandlung/OP.CI Implantation.Cochlear... Nucleus Profile CI532 (Slim Modiolar)": "feature_labels.implant_ci532",
  "Behandlung/OP.CI Implantation_Behandlung/OP.CI Implantation.Cochlear... Nucleus Profile CI522 (Slim Straight)": "feature_labels.implant_ci522",
  "Behandlung/OP.CI Implantation_Behandlung/OP.CI Implantation.Advanced Bionics... HiRes Ultra (HiFocus SlimJ)": "feature_labels.implant_ab_hires_ultra_slimj",
  "Behandlung/OP.CI Implantation_Behandlung/OP.CI Implantation.Advanced Bionics... HiRes Ultra 3D (HiFocus Mid-Scala)": "feature_labels.implant_ab_hires_ultra3d_mid",
  "Behandlung/OP.CI Implantation_Behandlung/OP.CI Implantation.Advanced Bionics... HiRes Ultra 3D (HiFocus SlimJ)": "feature_labels.implant_ab_hires_ultra3d_slimj",
  "Behandlung/OP.CI Implantation_Behandlung/OP.CI Implantation.Cochlear... Nucleus Profile Plus CI612 (Contour Advance)": "feature_labels.implant_ci612",
  "Behandlung/OP.CI Implantation_Behandlung/OP.CI Implantation.Cochlear... Nucleus Profile Plus CI622 (Slim Straight)": "feature_labels.implant_ci622",
  "Behandlung/OP.CI Implantation_Behandlung/OP.CI Implantation.Cochlear... Nucleus Profile Plus CI632 (Slim Modiolar)": "feature_labels.implant_ci632",
  "Behandlung/OP.CI Implantation_Behandlung/OP.CI Implantation.MED-EL... Implantattyp, Elektrodentyp": "feature_labels.implant_med_el",
  "Behandlung/OP.CI Implantation_Behandlung/OP.CI Implantation.Oticon Medical... Neuro Zti EVO": "feature_labels.implant_oticon_neuro",
  "Objektive Messungen.4000 Hz..._Keine Reizantwort": "feature_labels.objective_4000_no_response",
  "Objektive Messungen.LL..._Keine Reizantwort": "feature_labels.objective_ll_no_response",
};

export function getFeatureLabelKey(raw: string): string | undefined {
  return FEATURE_LABEL_KEYS[raw];
}
